version: '3.8'

services:
  backend:
    build: ./backend
    container_name: radar-backend
    restart: unless-stopped
    environment:
      - PORT=5000
      - JWT_SECRET=Kumteltechradar12@
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin1234
    volumes:
      - sqlite-data:/app/db

    ports:
      - "8088:5000"
    networks:
      - radar-net

  
volumes:
  sqlite-data:

networks:
  radar-net:
    driver: bridge